# Generated by Django 4.1.2 on 2022-10-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
